### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by jlanctot** [bbloomf/christmas-carols#1]
Hello Benjamin!

My choir--http://festivalchoirmadison.org/--is so pleased to find an excellent collection of public-domain carols! I wanted to make sure we're using this music appropriately and giving you the credit you deserve:
(1) In the work, you mention that "this work is free of known copyright restrictions." I wanted to make sure that this statement means _you_ were also relinquishing any copyrights as the person responsible for putting this together.
(2) If there's some kind of copyright reserved on the work, I wanted to ask permission to take selections to create our own "gig book" of carols with other works.
(3) Regardless of the answers to (1) and (2), I wanted to know if you accepted donations to keep this collection active. I think this is a great project and wanted to recognize and encourage this work!

Thanks!

Jon Lanctot
President, Festival Choir of Madison

**Comment by bbloomf** [comment]
I am so glad to hear that you are interested in my collection of Christmas
carols.  I am also pleased to tell you that I am indeed relinquishing any
copyright, and intend to keep everything in the public domain, so please
feel free to use the book however you want, make derivative works, etc.

I have never been offered a donation before, but I would happily accept one
as incentive to keep up the book.  I suppose you could send me a donation
through Google or if you would prefer to mail a check, I could send you my
address.

Thanks,

Benjamin Bloomfield

P.S. I am traveling right now, so I may not respond again until the weekend.
