### ISSUE TITLE
Some font issue when using the lilypond script (e.g. Silence Night) on both Windows and Mac

### ISSUE THREAD

**Issue by KowloonWalledCityCoin** [bbloomf/christmas-carols#2]
The PDF show something like smallCapsOldStyle  oldStyleNum and a mix of something like "smallCoaldpSstOyldeSPatygleNcuhmristmas" on the top few rows of the PDF.  Otherwise, the PDF seems goods:

[035-Silent Night-display-issues.pdf](https://github.com/bbloomf/christmas-carols/files/64036/035-Silent.Night-display-issues.pdf)

**Comment by bbloomf** [comment]
Do you have the util.ly in a place where Lilypond can find it?  That is where the \smallCapsOldStyle and \oldStyleNum commands are defined.  Otherwise, you can just remove those commands if you don't care about old style numbers and small caps

**Comment by KowloonWalledCityCoin** [comment]
Thanks for the quick response.  I did change the location to point to the util.ly so that the error not found is resolved.  Problem still there therefore I post my question.  I would do a bit more testing and learning tomorrow.  Btw, learn a lot in studying your code.  Thanks again.

**Comment by KowloonWalledCityCoin** [comment]
Re-test it and it seems fine except with some Japanese Font.  Probably not your issues.  Sorry to distribute you.  

[035-Silent Night-test2-mac.pdf](https://github.com/bbloomf/christmas-carols/files/65209/035-Silent.Night-test2-mac.pdf)

Seems even English Win10 (and Chines Win 7) would give you

[035-Silent Night-test2-S100-eng-win10-32.pdf](https://github.com/bbloomf/christmas-carols/files/65304/035-Silent.Night-test2-S100-eng-win10-32.pdf)

BTW, if I select a few and cut all but one voice to start the journey to make an open book for christmas carol on github for violin, would that be ok?

**Comment by bbloomf** [comment]
Certainly, that would be fine.  I made the source available in hopes that it would be useful to other people, so I'm happy for you to use it in whatever way you want.

Thanks,

Benjamin Bloomfield
