### ISSUE TITLE
"Es ist ein Ros entsprungen" alto notes

### ISSUE THREAD

**Issue by maiamcc** [bbloomf/christmas-carols#3]
Hi there!

I'm putting together a carol collection of my own and have been using some of your files as starting points---thank you for your work in putting this together, and making it available for others!

I noticed a note error in _Es ist ein Ros entsprungen_ in the alto part at the very end. Your edition has the last two bars of the alto part:
```
  g4 e fis2( |
  d4) d d2 \bar "|."
```
when it should read:
```
  g4 e fis8( g |
  a d,4) d2 \bar "|."
```

See e.g. [this video](https://youtu.be/Ru0JYOBre7Y?t=52s).

Also, every version of this piece I've ever sung has the text `von Jes -- se kam __ die Art` -- Wikipedia has the text you've provided (`war die Art`) but I can't find any other source.

Thanks for this great resource!

**Comment by maiamcc** [comment]
...hmm, found a few other note errors. I'm changing the engraving a bit for my version anyway, I can just make a pull request!

**Comment by bbloomf** [comment]
Fixed in latest commit.  Thanks for letting me know about this.
