### ISSUE TITLE
Stille Nacht author typo

### ISSUE THREAD

**Issue by davidpiano** [bbloomf/christmas-carols#6]
The author's surname on the original Stille Nacht lyrics is currently Möhr, but should be changed to Mohr.

Your whole collection is beautifully done - thank you for making it available.

**Comment by bbloomf** [comment]
Thanks.  I wonder where that error came from.  I knew I should have double checked all the metadata.  I have fixed the source files, and I will build a new PDF tonight or over the weekend.
