### ISSUE TITLE
File name discrepancies for "Lætentur Cæli"

### ISSUE THREAD

**Issue by JDLH** [bbloomf/christmas-carols#7]
I compared the names of the MIDI files linked to from http://acollectionofchristmascarols.com/ index, against the names in the carols list. There are two discrepancies from one carol. 

1. Carol "Lætentur Cæli" links to file named [`Lætentur Cœli.midi`](http://acollectionofchristmascarols.com/downloads/L%C3%A6tentur%20C%C5%93li.midi). Filename uses 'œ', but list uses 'æ', in "Cæli". The contents of the score spell "Cæli" exclusively. I did a bit of web searching, and it seems "Cæli" is more likely right, and "Cœli" is more likely wrong. The file name should be spelled `Lætentur Cæli.midi`.
2. Source file for carol "Lætentur Cæli" is `183-Laetentur Coeli.ly`. This should perhaps be `183-Laetentur Caeli.ly` ('ae' instead of 'oe').

I would offer a patch, but in reading through `make.js` and friends, I don't see how either the MIDI files or the index page of the website get generated.

Thank you for this awesome carol book! I found out about this project because some friends were singing carols (outdoors, distanced) using it.

**Comment by bbloomf** [comment]
Thanks!
